---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: github-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-user
subjects:
- kind: ServiceAccount
  name: github-user
  namespace: kube-system